### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bimboengineer** [avaidyam/Parrot#104]
Its been 3 months since we have seen an update, and so far there are still many bugs. Is an update coming, or is this project dead?

**Comment by avaidyam** [comment]
The project is definitely not abandoned! I'll be pushing updates slowly, but we're still kicking here. It's just me after all. 😄

**Comment by avaidyam** [comment]
@jjisawesome Please do make a ton of bug reports, most of the issues you may be seeing are hard for me to trace down without reports. 👍

**Comment by bimboengineer** [comment]
Cool! Thanks! I will be sure to detail all the bugs that I see. I am eager to see what updates you push in the future!

**Comment by avaidyam** [comment]
@jjisawesome Thanks! To be honest, I'm just glad people use this app at all. 😆

**Comment by bimboengineer** [comment]
I really love having hangouts out of the browser bc I have literally 10 google accounts but only 1 main one.

**Comment by avaidyam** [comment]
That reminds me, multi-account support does exist in technicality but there is no UI for it.

**Comment by bimboengineer** [comment]
Oh?

**Comment by bimboengineer** [comment]
thats really exciting!

**Comment by avaidyam** [comment]
😄 Regardless, thanks for your interest - I'll be pushing out updates soon-ish.

**Comment by bimboengineer** [comment]
do you have Mojave support ironed out yet?

**Comment by avaidyam** [comment]
@jjisawesome Working on that slowly at the moment, which is why there's a lack of updates (coupled with my personal stuff.)

**Comment by bimboengineer** [comment]
cool!

**Comment by avaidyam** [comment]
@jjisawesome As you can see I just pushed every change I had been saving up on. 😉

**Comment by bimboengineer** [comment]
Thanks so much!
