### ISSUE TITLE
Can't build on High Sierra

### ISSUE THREAD

**Issue by bimboengineer** [avaidyam/Parrot#106]
Is the latest version (commit 6cf7ba4)comparable with High Sierra? I am getting 217 on hangouts core when building. (This is after making sure the code signing is set up right)

**Comment by avaidyam** [comment]
You need to use Xcode 10.0 and Swift 4.2. I suggest using a stable release for now.

**Comment by bimboengineer** [comment]
I still need to upgrade to 10.0 with Mojave, so that explains it.
