### ISSUE TITLE
Missing Alamofire

### ISSUE THREAD

**Issue by lucasderraugh** [avaidyam/Parrot#2]
When I clone this project, it seems it is missing Alamofire. I could add this in but I'm wondering what approach you'd want to take for this? I'd personally prefer either Carthage or git submodules.

**Comment by avaidyam** [comment]
I actually don't like the use of Carthage or CocoaPods for dependency management, and git submodules would work, but I just want to temporarily use the framework alone.

Keep in mind: the goal is to reduce external dependency. The majority of Alamofire usage can be replaced with `NSURLSession` et al, it'll just take time.

**Comment by lucasderraugh** [comment]
I agree, really not a fan of the external dependency managers. Would you like to move everything to NSURLSession instead or just include Alamofire as a submodule for now?

**Comment by avaidyam** [comment]
I'd rather try to move towards `NSURLSession`, as we're not using a majority of the fancy Alamofire features. I gave it a brief thought a few weeks ago, but a lot of this work on Parrot was done while procrastinating for final exams... 

One of the big reasons why I'm pushing away from Alamofire is eventual cross-compatibility. There's no reason to suggest that Alamofire will remain OS X-only even after the Foundation framework is rewritten in Swift. Likewise, I believe if Parrot is made of many moving parts that should and can be used on their own, it should remain dependency-free and as "cross-platform" as possible. I've been investigating an Android port of Swift, which seems to work with the bare minimum, but again, Foundation's URL handling part hasn't been rewritten in Swift, so there goes that.

**Comment by avaidyam** [comment]
@lucasderraugh I've done a fair amount of work in removing the Alamofire overhead, but there's only one spot I'm having issues with right now:

```
manager.request(request).stream { (data: NSData) in self.onPushData(data) }.responseData { response in
```

I can't seem to figure out how to replicate the `stream` call without messing up the delegates.

An idea is to clone the `SessionDelegate` and in the extension `request` function, automatically hook it up. I may try this out later. Any suggestions?

**Comment by avaidyam** [comment]
I've added in the bit I mentioned about `SessionDelegate`, but it doesn't seem to fully work yet.

**Comment by avaidyam** [comment]
@lucasderraugh Alamofire has been removed from the dependencies; you should no longer need it.
