### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by matthewdias** [avaidyam/Parrot#20]
Using the release version. Not sure if this is related to #2 
http://pastebin.com/b46RWrN7

**Comment by avaidyam** [comment]
@matthewdias Hold tight, there were several breaking changes to Hangouts that I patched. You can try compiling from source if you want to, but I'll put up a new release now.

**Comment by avaidyam** [comment]
@matthewdias https://github.com/avaidyam/Parrot/releases/tag/0.2

Try that. :)
