### ISSUE TITLE
Build links

### ISSUE THREAD

**Issue by asci** [avaidyam/Parrot#21]
I didn't get how to start an app.

Can you provide please links to build a project if it possible?

**Comment by avaidyam** [comment]
Did you try downloading the release 0.2 or building it yourself?

**Comment by 3871968** [comment]
I am also not able to build this from the source because of a provisioning profile issue. Could you possibly turn off code signing?

**Comment by avaidyam** [comment]
It's always a bad idea to turn off code signing for no reason -- have you tried changing the certificate in the product settings to "`-`"? That essentially disables it.

**Comment by avaidyam** [comment]
Also note that you have to build `Alamofire.framework` separately and place it in the `External` folder.

**Comment by asci** [comment]
Where can I download the release 0.2?

**Comment by avaidyam** [comment]
@asci https://github.com/avaidyam/Parrot/releases
