### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by matthewdias** [avaidyam/Parrot#22]
Parrot just shows a blank screen, and doesn't have the option to log out. This is porbably because i switched from a self-compiled version to the release. Is there a way to clear its data so I can start fresh with the login flow?

**Comment by avaidyam** [comment]
@matthewdias Did this work out for you?

**Comment by matthewdias** [comment]
yeah, all good

**Comment by avaidyam** [comment]
Great! :+1: Sorry I couldn't get back to you. Been a bit busy with life.

**Comment by matthewdias** [comment]
Haha, no problem. I totally get it.

**Comment by avaidyam** [comment]
:smile:
