### ISSUE TITLE
Blank Screen on open - no application identifier provided

### ISSUE THREAD

**Issue by blaedj** [avaidyam/Parrot#27]
Using the v0.3-alpha pre-compiled binary on OSX 10.11, all I see is a blank screen with the title 'Login to Parrot'. 
Looking in console.app, the below message appears in the logs every time I open the app. 

`taskgated[473]: no application identifier provided, can't use provisioning profiles [pid=85051]`

I'm able to open, run and log in using the previous released version.

**Comment by gattilorenz** [comment]
same problem here (10.11.5 and same error message)

**Comment by avaidyam** [comment]
Huh, weird. It looks like a provisioning profile issue, then. I'll test it out on a separate Mac real quick.

It could be Xcode 8's new provisioning profile management thing.

**Comment by avaidyam** [comment]
The bug should be fixed, and [the release has been updated!](https://github.com/avaidyam/Parrot/releases/tag/v0.3-alpha)

@gattilorenz @blaedj Let me know if it works!

**Comment by blaedj** [comment]
Yep I can log in now thank you!

**Comment by avaidyam** [comment]
@blaedj Awesome! How do you like Parrot? 😉

**Comment by gattilorenz** [comment]
@avaidyam thanks for squashing the bug! 

Parrot seems still a bit rough around the edges, but it's incredible to have a _real_ native hangout  client... I can finally close the browser! <3

If I may suggest an improvement (or is it there, but I'm just unable to see it?), it's sending message with [Return] and adding a CRLF with [Shift]+[Return]... it's a bit annoying (not to mention much slower) to click the button everytime. Other than that, thank you so much for the great work!

**Comment by avaidyam** [comment]
@gattilorenz Right!? It's shocking this isn't a priority. 

The feature you requested was there in an earlier build, and it's something I personally really want, so it'll come back. I'm transitioning the UI slightly and then it should be fine. 👍

**Comment by blaedj** [comment]
It's awesome to have an actual native client like gattilorenz said, thanks for all your work and I hope I can help out
