### ISSUE TITLE
Contact list gone after closing

### ISSUE THREAD

**Issue by bbickerton** [avaidyam/Parrot#35]
Parrot v0.6-alpha
macOS Sierra 10.12.1

After closing the contact list, there's no way to get it back without restarting the app.

Steps to Reproduce:
1. Start Parrot and log in if necessary
2. Close the contact list with the red (x) button in the top left.
3. Parrot is still running, with no way to show the contact list again.
4. Restart Parrot to bring contact list back.

**Comment by avaidyam** [comment]
Actually, there currently is a way: right click on the dock and select `Open Conversations`. I should probably make it open when the dock icon is pressed a second time though... I'll keep this issue open until that change happens.
