### ISSUE TITLE
Broken unread badge

### ISSUE THREAD

**Issue by bbickerton** [avaidyam/Parrot#36]
Parrot v0.6-alpha
macOS Sierra 10.12.1

The unread badge on the app dock icon has two issues for me.
1. It increments up for messages I send.
2. It doesn't clear when the chat with new messages is brought in focus (and continues to increment as messages come in). The badge count remains even after closing a chat window and reopening it.

**Comment by avaidyam** [comment]
Ah yeah. I see that issue too -- I'm working on a better fix. I'm wondering if it should represent `unread conversations` or `unread messages per conversation`. I was previously using the Hangouts definition...

**Comment by avaidyam** [comment]
I think I've figured it out, @TauZero, some internal Hangouts events can't be "observed" using the normal API and thus they always show up as unread. I'll look into fixing that -- sorry I'm almost a year late on this.

**Comment by avaidyam** [comment]
I should have patched it. Let me know (when it's released) if v0.8 has the issue still.
