### ISSUE TITLE
parrot-cli crashes due to lack of libSwiftCore.dylib

### ISSUE THREAD

**Issue by saagarjha** [avaidyam/Parrot#46]
I'm consistently getting this error message when trying to run parrot-cli:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/saagarjha/Library/Developer/Xcode/DerivedData/Parrot-godzscpqujfrhrabsatakfyqgmdu/Build/Products/Debug/Mocha.framework/Versions/A/Mocha
  Reason: image not found
```

If I didn't know any better, I'd suggest that Mocha had `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` set to `NO` in the Build Settings, but for some reason setting it to `YES` only seems to fix it in Xcode's console…

**Comment by avaidyam** [comment]
The intended method of running it is to invoke `./Parrot.app/Contents/MacOS/parrot-cli`. `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES` is something I actively try to avoid. If it's working for you in the Xcode console but not outside of it, you're probably running it wrong.
