### ISSUE TITLE
Hide Dock Icon (and live in MenuBar)

### ISSUE THREAD

**Issue by vanshg** [avaidyam/Parrot#49]
Would it be possible to add an option to hide the dock icon and make parrot live in the MenuBar. That way I can keep it always running and not have an icon in my Dock. It'd just be cleaner :)

**Comment by vanshg** [comment]
I cloned the repo to play around a bit and see how this could be done. It should actually be fairly simple. Another setting could be added in the Experimental Section. Add a `LivesInMenuBar` string to the `Parrot` settings enum. Then, based on whether that box was checked or not, in `applicationWillFinishLaunching`, you could do something along the lines of

```
let statusItem = NSStatusBar.system().statusItem(withLength: -1)
        if let button = statusItem.button {
            button.image = NSImage(named: "StarIcon")
        }
        let menu = NSMenu(title: "Parrot")
        menu.addItem(title: "Open Conversations") {
            log.info("Open Conversations")
            DispatchQueue.main.async {
                self.conversationsController.showWindow(nil)
            }
        }
        menu.addItem(withTitle: "Log Out...",
                     action: #selector(self.logoutSelected(_:)),
                     keyEquivalent: "")
        statusItem.menu = menu
```

Also you would need to modify the Info.plist file to set `Application is agent (UIElement)` to `YES`. This would make the Dock Icon go away. I'm not sure how to set this dynamically though.

Making these changes, I had a somewhat working implementation of living in the MenuBar, but for some reason, the menu bar icon does not stay in the system tray. I'm not a macOS/iOS/Swift developer, so I'm not really sure why this is happening, but I'm sure you (@avaidyam) could help out here

**Comment by avaidyam** [comment]
While this is trivial like you said, right now I don't have the UI components ready to the state that I would like to even have this as an experimental option. I don't believe it's as simple as the status item toggling the Conversations window, and that's why it hasn't been implemented yet. You are *more than welcome* to roll this change to your local copy and use it as you please. 

Also, note, modifying the `LSUIAgent` (I think that was it) key is a pretty bad idea if you are trying to build a dynamic app. There are other ways of doing this.

**Comment by vanshg** [comment]
I've got a fork going where the app *only* lives in the Menu Bar, if you want to take a look

https://github.com/vanshg/Parrot

**Comment by avaidyam** [comment]
A rudimentary menubar support has been added. It doesn't support unread indicators and must be manually activated by adding the `LSUIElement` key to the `Info.plist` and sending a `defaults write` on the `Parrot.MenuBarIcon` key. For now, I'll keep it like this until more of Parrot is fleshed out.

**Comment by vanshg** [comment]
Awesome, thanks!
