### ISSUE TITLE
Can't start new conversation

### ISSUE THREAD

**Issue by bennettscience** [avaidyam/Parrot#50]
Using Parrot 0.6-alpha, the search button in the conversation list doesn't open anything and I can't start a new conversation. Incoming messages are added and I can pick up from there, but I can't start a new one from the app.

**Comment by avaidyam** [comment]
Correct -- the functionality isn't there yet in the UI, but it works in the framework. I'll be patching things up in the coming month so stay tuned.

**Comment by bennettscience** [comment]
Not sure what was going on earlier. New conversations are starting as expected. I can close this issue if you'd like.

**Comment by avaidyam** [comment]
That's quite odd... I don't recall "wiring up" the ability to start a new conversation, lol. What exactly did you do?

**Comment by bennettscience** [comment]
I'm probably not being clear. Earlier, when I clicked on an existing conversation, nothing would happen. I closed and reopened the next day and the conversation window opened. I still cannot _initiate_ a conversation from scratch, which makes sense if you haven't implemented yet.

**Comment by avaidyam** [comment]
@bennettscience Got it, that makes sense but is a little weird. I'll look into that better.
