### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eklavya** [avaidyam/Parrot#54]
Hi @avaidyam 

Been waiting for a stable release for so long! Please make a new release?

Thanks :)

**Comment by avaidyam** [comment]
Hey! Thanks so much for your support. I'm currently retooling a lot of things internally but I'm getting close to v0.7. Thanks for waiting this long!

**Comment by eklavya** [comment]
Thanks for the update @avaidyam :)

**Comment by avaidyam** [comment]
@eklavya `v0.7-alpha` is all set to go!

**Comment by eklavya** [comment]
Yay! let me check it out. Does it get messages from when you were not online now?

**Comment by avaidyam** [comment]
It should... make issues for every tiny thing you find is even slightly off or not working this release. v0.8 will be mostly a bug fix release to make it reliable.
