### ISSUE TITLE
Preferences don't work

### ISSUE THREAD

**Issue by eklavya** [avaidyam/Parrot#66]
Nothing happens when I click different tabs. The same screen is shown for everything.

![preferences](https://user-images.githubusercontent.com/1136647/27365676-fff6797e-565e-11e7-9026-0790b2e69a33.jpeg)

**Comment by avaidyam** [comment]
@EdenSG @eklavya @wakest @vanshg: I haven't been able to reproduce this issue in a long while so I'll close this for now. Let me know if there's an update to this issue and I can reopen it.
