### ISSUE TITLE
Single window view?

### ISSUE THREAD

**Issue by eklavya** [avaidyam/Parrot#68]
Is there a single window mode? I couldn't find any option for it.

**Comment by avaidyam** [comment]
Not publicly available yet, but I've seen it and it works well, so likely in v0.8... 😉

**Comment by avaidyam** [comment]
@eklavya I've enabled this on the most recent commit, but there are a few glitches in the toolbar - you won't be able to start a new conversation or see the participants/info of a conversation yet.

**Comment by avaidyam** [comment]
It's all working well now @eklavya and will be in a new release soon.
