### ISSUE TITLE
Conversation should scroll to show new messages

### ISSUE THREAD

**Issue by clee** [avaidyam/Parrot#82]
If the user hasn't scrolled back in the conversation log, the conversation should autoscroll when new messages appear.

**Comment by avaidyam** [comment]
@clee Did you mean that when a new message arrives, the window would scroll-to-bottom? Because I suppose I find that behavior a little upsetting when I try to read old messages. I'm looking into adding an index to the scrollbar (the little thing in iOS's Contacts.app when you drag the scrollbar) that could notify the user of new messages.

**Comment by clee** [comment]
> I suppose I find that behavior a little upsetting

Right, everybody does, which is why I said “if the user hasn’t scrolled back in the conversation log”. If I’m actively having a conversation, I do not want to have to keep moving my right hand to scroll the conversation to see new messages. But, *at the same time*, I would also like to not have the scroll position changed IF I have manually scrolled back up to read. So the conversation log should auto scroll to display new messages if and ONLY if the user is currently scrolled to the very end of the log already.

**Comment by avaidyam** [comment]
Ah that's what you meant -- I misunderstood. The scroll index thing I'm looking into will likely solve this issue. [The conversation technically *does* autoscroll, but it's buggy.](https://github.com/avaidyam/Parrot/blob/master/Parrot/MessageListViewController.swift#L519)

**Comment by avaidyam** [comment]
@clee I've just fixed this and can confirm it works on my end in the latest Parrot build. I'll be pushing a new release soon.

**Comment by clee** [comment]
@avaidyam Awesome! Looking forward to trying it out :)
