### ISSUE TITLE
1.0 versioning

### ISSUE THREAD

**Issue by vanshg** [avaidyam/Parrot#92]
Hey, is there an ETA on when 1.0 will be released? If Parrot's in a somewhat stable state, it'd be great if it could be released as a 1.0, and then additional features added through minor version updates!

**Comment by avaidyam** [comment]
@vanshg I think I'm at a good point for v0.9 since most features are in and things are looking alright on my end. I'll go ahead and push that in a few hours. v1.0 will probably be before summer, it looks like - just bugs to squash and two major features to add.

**Comment by avaidyam** [comment]
@vanshg [Here's v0.9 - let me know of any bugs you encounter.](https://github.com/avaidyam/Parrot/releases/tag/v0.9-alpha)
