### ISSUE TITLE
Desktop Icon

### ISSUE THREAD

**Issue by maximtart** [avaidyam/Parrot#93]
Hi there,
your app is very nice and cute but when I've tried to run it from source code I've found very strange behavior (bug maybe).
All my desktop icons was appeared over all windows and I can't select any window by mouse click.
For fix this I must to restart system or logout.

Please see attached screenshot.

![screen shot 2018-03-06 at 12 01 31 am](https://user-images.githubusercontent.com/975675/37002401-452aa63a-20d2-11e8-95d1-0dceb4ef963c.png)

**Comment by avaidyam** [comment]
That's pretty odd. I think I know the fix though. I'll get back to you on that soon.

**Comment by maximtart** [comment]
hi
After few hours of debugging and restarting my system, I have found something.
When I've turned off notification window(window with label "Parrot is connected"), everything works well. 

Maybe it will help you.

**Comment by avaidyam** [comment]
Yup, it's the use of the private Spaces API that is leading to undefined behavior.

**Comment by avaidyam** [comment]
Yup, it's the use of the private Spaces API that is leading to undefined behavior.

**Comment by avaidyam** [comment]
Yup, it's the use of the private Spaces API that is leading to undefined behavior.

**Comment by avaidyam** [comment]
@Leadro Take a look at the recent commit - if you'd rather home-patch Parrot, line 85 in `NSWindow+Transforms.swift` (in MochaUI) should be 
```
        let flag = 0x1 // this value MUST be 1, otherwise, Finder decides to draw desktop icons
        self.identifier = CGSSpaceCreate(_CGSDefaultConnection(), flag, nil)
```

This fixes the issue described. I turned off Finder's `CreateDesktop` flag so I hadn't noticed the issue. Thanks for the bug! 👍
