### ISSUE TITLE
Parrot 0.9-alpha fails to launch properly

### ISSUE THREAD

**Issue by clee** [avaidyam/Parrot#94]
I'm running macOS 10.13.1 on a 13-inch Retina MacBook Pro from 2015. I was using Parrot 0.7-alpha and it launched fine even if it was a little buggy and crashy.

After downloading 0.9-alpha directly from the [releases page](https://github.com/avaidyam/Parrot/releases), I unzipped it by double-clicking the zip file and then double-clicked on the Parrot.app. 
![screen shot 2018-03-16 at 2 47 01 pm](https://user-images.githubusercontent.com/2089/37543992-10a90640-2929-11e8-9b27-c87908a77f79.png)

**Comment by avaidyam** [comment]
I've noticed a few people having this issue. Can you see if turning off gatekeeper, opening the app, and then turning gatekeeper back on, works?

**Comment by avaidyam** [comment]
Also, could you send me any of the crash logs from Parrot v0.7!? 😊 I would love to patch the issues.

**Comment by clee** [comment]
I can't disable Gatekeeper, unfortunately (my work prevents that ability entirely).

I can see about the crash logs!

**Comment by avaidyam** [comment]
I think it has to do with the codesign certificate on my end. I'll try to re-sign a new binary today or tomorrow and let you know.
