### ISSUE TITLE
New messages aren't formatted properly

### ISSUE THREAD

**Issue by clee** [avaidyam/Parrot#96]
Attaching a screenshot to demonstrate. (The messages that are easily-legible are from conversation history pulled from Hangouts; the last one at the bottom from me that's almost impossible to read is one I sent in Parrot.)

<img width="425" alt="screen shot 2018-03-27 at 2 11 18 pm" src="https://user-images.githubusercontent.com/2089/37992593-6ac99d58-31c9-11e8-85c4-f780d05c3e2e.png">

**Comment by avaidyam** [comment]
A temporary workaround is to se the background color of the bubbles manually (press the cog at the top right and you'll be able to set different you/them colors).

**Comment by avaidyam** [comment]
@clee I think I've fixed this one too - just a little longer!
