### ISSUE TITLE
Parrot 0.7 crashes

### ISSUE THREAD

**Issue by clee** [avaidyam/Parrot#99]
I don't remember what I was doing during these crashes, but I found the crash logs here so I wanted to upload them.

[Parrot_2018-03-15-144812_clee.crash.gz](https://github.com/avaidyam/Parrot/files/1853797/Parrot_2018-03-15-144812_clee.crash.gz)

[Parrot_2018-03-15-144839_clee.crash.gz](https://github.com/avaidyam/Parrot/files/1853799/Parrot_2018-03-15-144839_clee.crash.gz)

**Comment by avaidyam** [comment]
@clee Thanks so much! I'll take a look at them today and this week. 👍

**Comment by avaidyam** [comment]
@clee Actually, it looks like I encountered this same issue from your crashes and have already solved it. *I think.* If it comes up again, please file another issue or reopen this one! 😄

**Comment by clee** [comment]
You got it! Thanks, Aditya :)​
